# This file was generated by GoReleaser. DO NOT EDIT.
class ClusterCaution < Formula
  desc "Prevents execution errors in kubectl"
  homepage "https://github.com/pyama86/cluster-caution"
  url "https://github.com/pyama86/cluster-caution/releases/download/0.1.0/cluster-caution_0.1.0_darwin_amd64.tar.gz"
  version "0.1.0"
  sha256 "7cee1418d30d2ffe360e11709dacfcb1e2cde2387ac0741e9a461232cbce3c93"

  def install
    bin.install 'kubectl-caution'
  end

  test do
    system "#{bin}/kubectl-caution"
  end
end
